server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyeminboard
    username: root
    password: 1q2w3e4r


mybatis:
  mapper-locations:
    - /mappers/*.xml